name: vet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^6.0.0
  flutter_lints: ^3.0.1

flutter:

  assets:
    - assets/images/
    - assets/images/logo.svg
    - assets/images/navigation.svg

  uses-material-design: true

